### PR TITLE
Configurable service actions

### PR DESCRIPTION
**Pull request by vivid-inc**
As mentioned in #135 , a PR is a capital idea!

### CODE REVIEW

**Comment by phlipper** [comment]
@vivid-inc thank you very much for this! I rebased it on top of the latest master and cleaned it up a bit, and merged it in as #139.

**Comment by vivid-inc** [comment]
Thanks -- Looking forward to the next release!

**Comment by phlipper** [comment]
@vivid-inc this has now been released with `0.16.1`

**Comment by vivid-inc** [comment]
Great!

**Pull request closed without merging**
